### ISSUE TITLE
Using multiple servers

### ISSUE THREAD

**Issue by imurs34** [xychang/RecursiveHierarchicalClustering#10]
Hello, I am very impressed by your wonderful research!
Thank you for sharing it!

But, I faced a problem of using multiple servers,
I thought that the temporary files(.pkl files) are also created in the multiple servers. But even though it doesn't create temporary files in remote servers, I think it looks for the files in remote servers, creating errors.

Again, thank you for your work.

**Comment by xychang** [comment]
The multi-server code was written for clusters with shared file systems. If you are running it on different machines with no shared storage, then some serious changes are required to make it work.

**Comment by imurs34** [comment]
Crystal clear, thank you!
