### ISSUE TITLE
setting threadNum and minPerSlice

### ISSUE THREAD

**Issue by imurs34** [xychang/RecursiveHierarchicalClustering#13]
Hello, thank you for your wonderful project again, and I'm striving to run the clustering across 2 AWS EC2 servers. I modified code, and it successfully accesses to 2 servers with small input file. But the thing is that, it does not work with the large input file(~700000 users), so I wonder how I should set the threadNum and minPerSlice to work with 2 servers and 700000 users input.

Is there any further explanation on setting threadNum and minPerSlice to use all of the servers listed in 'servers' variable in servers.json?

Thank you for your amazing project again!

**Comment by Symash** [comment]
To be more specific with this phrase: "it does not work with the large input file(~700000 users)", if I run with threadNum = 5 and minPerSlice = 1, after showing '[LOG]: start new thread 5' in cmd, when I check on the servers, the program would be only running in localhost but not in the second server.

Thanks for your help in advance!

**Comment by imurs34** [comment]
It was due to .pem file, thanks!
