### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by AliceGab** [xychang/RecursiveHierarchicalClustering#3]
Hi, 

I read your paper and found it very interesting so I am trying to implement it. I noticed an inconsistency between the paper and the codes, namely in the paper the events stream is processed as A(g1)D(g2)A(g2)C(g3) where A,C,D are events and g1, g2, g3 the gaps between each event whereas in the codes, it seems (from the README and the way the sparse matrix is constructed) that the events are processed as A(na)D(nd)C(nc), where A,C,D are events and na,nc,nd are their respective occurence in the user's history. 

If we do an analogy with NLP, the version on the paper sounds more like a sequence model whereas the second one more like a bag-of-word model, which I expect to give different clustering results.

Could you please clarify which processing I should follow ? 

Thanks!

**Comment by xychang** [comment]
Hi,
The code in GitHub is meant to be general purpose which allows for arbitrary features beyond action-gap-action. This means, `A` itself is a token for an action-gap-action tuple.

You can checkout this issue for more details:
https://github.com/xychang/RecursiveHierarchicalClustering/issues/2 <https://github.com/xychang/RecursiveHierarchicalClustering/issues/2>

Best,
Xinyi

**Comment by AliceGab** [comment]
OK got it! Thanks a lot
