### ISSUE TITLE
Unable to run on sample data provided

### ISSUE THREAD

**Issue by fafz1234** [xychang/RecursiveHierarchicalClustering#5]
Hi @xychang,
Thank you for providing this work. I wanted to test this approach for a project I am working on, but first I tried to simply run the code with the example input provided. 

 `python recursiveHierarchicalClustering.py input.txt output/ 0.05`

However, I got a `ZeroDivisonError` and was not able to create the result.json output for further examination. 

Here's what my output looks like:
```
[LOG]: total users 200
[LOG]: starting in localhost for tmp_1570654341_root
[LOG]: 2019-10-09 16:52:21.887000 computing matrix for output/tmp_1570654341_root
[LOG]: start new thread 1
[LOG]: 2019-10-09 16:52:25.918000 matrix computation finished for output/tmp_1570654341_root
computing matrix taking 4.037000s
matrix size 1
Traceback (most recent call last):
  File "recursiveHierarchicalClustering.py", line 975, in <module>
    treeData = runDiana(outPath, sid_seq, matrixPath=matrixPath)
  File "recursiveHierarchicalClustering.py", line 779, in runDiana
    baseMatrix, matrixBasics)
  File "recursiveHierarchicalClustering.py", line 529, in evaluateModularity
    return (firstEntry - secondEntry / m) / m
ZeroDivisionError: float division by zero
```

System info:
Python: 2.7.14
numpy: 1.14.0

Can you please help me resolve this issue?

**Comment by xychang** [comment]
I wasn't able to reproduce your error. I think one potential way to debug this is to look at the output folder and check if the matrix table is correct. 
Another potential thing to try is to run the optimized version instead. 
`recursiveHierarchicalClusteringFast.py`

**Comment by fafz1234** [comment]
Hi @xychang,
Thank you for the response. I have since resolved the issue.
