### ISSUE TITLE
Python version update

### ISSUE THREAD

**Issue by ywu-stats** [xychang/RecursiveHierarchicalClustering#6]
Thanks for sharing this very interested project. I'd love to try it for my analysis.
I'm on Python 3.7.3 and now having trouble of running the example code with input.txt.
Error message is
_" File "recursiveHierarchicalClustering.py", line 73
    def splitCluster((baseCluster, diameter, baseSum, cid), matrix):
                     ^
SyntaxError: invalid syntax_

My guess is the Python version issue. I'm new to Python though... Looking forward to any help here.
Thanks!

**Comment by xychang** [comment]
Yes, this is indeed a python version issue. The code used a syntax unique
to python2 which allows function input to be defined as nested structure.
It can be adapted by changing the function definition and processing the
input according to the input structure.
Unfortunately I don't have a lot of cycles to change the code. You are
welcomed to change it and send me a pull request!

**Comment by akhildevelops** [comment]
Hi @xychang ,

I will raise a PR for this.

**Comment by xychang** [comment]
That's great. Thank you very much!

**Comment by akhildevelops** [comment]
Hi @xychang 

I gave a PR : https://github.com/xychang/RecursiveHierarchicalClustering/pull/9

Pls check

Thx
