### ISSUE TITLE
local host in windows system

### ISSUE THREAD

**Issue by ywu-stats** [xychang/RecursiveHierarchicalClustering#7]
Thank you for getting back to me with my previous issue about python version. I switched to python2 and was able to run it at least. But new issue I encountered was the setting the server.config. I'm running it on my local computer which is windows 10 system. I tried several things and was able to access the localhost http://localhost:8000/. However, after change the setting to "server":["http://localhost:8000/"], I got following error IOError: [Errno 22] invalid mode ('w') or filename: u'out/tmp_1571936168_rootsid_http://localhost:8000/.pkl'. 
How can I fix it? Looking forward to your feedback.

**Comment by imurs34** [comment]
Oh, I'm having similar problem! Can you share your solutions if possible?
Thank you!

**Comment by ywu-stats** [comment]
You need to get to the code and change the naming of your local host. For example the line 209 in calculateDistance.py.
